const CONST = {
    LOGIN_ERROR_REQUIRED: 'Please fill out all fields',
    LOGIN_ERROR_WRONG_DATA: 'Email or Password Incorrect',
    LOGIN_ERROR_INVALID_DATA: 'Please register your email address',
    CHANGE_PWD_ALL_FIELDS_REQUIRED: 'All fields are required',
    VALID_PASSWORD: 'Password Must Contain at least 8 characters',
    PASSWORD_NOT_MATCH: 'Passwords do not match.',
    PASSWORD_SUCCESS: 'Password changed successfully.',
    UPDATE_ACCOUNT_SUCCESS: 'Account updated successfully.',
    CASH: [
        { value: '0', label: '0' },
        { value: '1', label: '1' },
        { value: '2', label: '2' },
        { value: '3', label: '3' },
        { value: '4', label: '4' },
        { value: '5', label: '5' },
        { value: '6', label: '6' },
        { value: '7', label: '7' },
        { value: '8', label: '8' },
        { value: '9', label: '9' },
        { value: '10', label: '10' },
        { value: '11', label: '11' },
        { value: '12', label: '12' },
        { value: '13', label: '13' },
        { value: '14', label: '14' },
        { value: '15', label: '15' },

    ],
    COC: [
        { value: '0', label: '0' },
        { value: '1', label: '1' },
        { value: '2', label: '2' },
        { value: '3', label: '3' },
        { value: '4', label: '4' },
        { value: '5', label: '5' },
        { value: '6', label: '6' },
        { value: '7', label: '7' },
        { value: '8', label: '8' },
        { value: '9', label: '9' },
        { value: '10', label: '10' },
        { value: '11', label: '11' },
        { value: '12', label: '12' },
        { value: '13', label: '13' },
        { value: '14', label: '14' },
        { value: '15', label: '15' },
    ],
    GRM: [
        { value: '0', label: '0' },
        { value: '1', label: '1' },
        { value: '2', label: '2' },
        { value: '3', label: '3' },
        { value: '4', label: '4' },
        { value: '5', label: '5' },
        { value: '6', label: '6' },
        { value: '7', label: '7' },
        { value: '8', label: '8' },
        { value: '9', label: '9' },
        { value: '10', label: '10' },
        { value: '11', label: '11' },
        { value: '12', label: '12' },
        { value: '13', label: '13' },
        { value: '14', label: '14' },
        { value: '15', label: '15' },
    ],
    PRICE: [
        { value: '50000', label: '$50,000' },
        { value: '100000', label: '$100,000' },
        { value: '150000', label: '$150,000' },
        { value: '200000', label: '$200,000' },
        { value: '250000', label: '$250,000' },
        { value: '300000', label: '$300,000' },
        { value: '350000', label: '$350,000' },
        { value: '400000', label: '$400,000' },
        { value: '450000', label: '$450,000' },
        { value: '500000', label: '$500,000' },
        { value: '550000', label: '$550,000' },
        { value: '600000', label: '$600,000' },
        { value: '650000', label: '$650,000' },
        { value: '700000', label: '$700,000' },
        { value: '750000', label: '$750,000' },
        { value: '800000', label: '$800,000' },
        { value: '850000', label: '$850,000' },
        { value: '900000', label: '$900,000' },
        { value: '950000', label: '$950,000' },
        { value: '1000000', label: '$1,000,000'},
        { value: '1250000', label: '$1,250,000'},
        { value: '1500000', label: '$1,500,000'},

    ],
    BED: [
        { value: '1', label: '1' },
        { value: '2', label: '2' },
        { value: '3', label: '3' },
        { value: '4', label: '4' },
        { value: '5', label: '5' },
        { value: '6', label: '6' },
        { value: '7', label: '7' },
        { value: '8', label: '8' },
        { value: '9', label: '9' },
    ],
    BATH: [
        { value: '1', label: '1' },
        { value: '2', label: '2' },
        { value: '3', label: '3' },
        { value: '4', label: '4' },
        { value: '5', label: '5' },
        { value: '6', label: '6' },
        { value: '7', label: '7' },
        { value: '8', label: '8' },
        { value: '9', label: '9' },
    ],
    UNITS: [
        { value: '2', label: '2' },
        { value: '3', label: '3' },
        { value: '4', label: '4' },
        { value: '5', label: '5' },
        { value: '6', label: '6' },
        { value: '8', label: '8' },
        { value: '10', label: '10' },
        { value: '15', label: '15' },
        { value: '20', label: '20' },

    ],
    OPTIONS: [
        { value: 'NewYork', label: 'NewYork' },
        { value: 'LosAngels', label: 'LosAngels' },
        { value: 'LosVegas', label: 'LosVegas' },
        { value: 'Califirnia', label: 'Califirnia' },
        { value: 'Texas', label: 'Texas' },
        { value: 'NewJersy', label: 'NewJersy' },
        { value: 'Alaska', label: 'Alaska' },
        { value: 'Colorado', label: 'Colorado' },
        { value: 'Florida', label: 'Florida' },
        { value: 'Indiana', label: 'Indiana' },
        { value: 'Oregon', label: 'Oregon' },
        { value: 'Utah', label: 'Utah' },
        { value: 'Virginia', label: 'Virginia' },
        { value: 'Washington', label: 'Washington' },
        { value: 'Wyoming', label: 'Wyoming' },
    ],
    PAGINATION_PAGES: 4,
    PAGE_SIZE: 25,
    PAGE_SIZES: [25, 50, 200],
    SAVE_DATA: ['minCash', 'maxCash', 'minPrice', 'maxPrice', 'minUnits', 'maxUnits', 'downCpy', 'interestCpy', 'yearsCpy', 'sortProp', 'sortAscDesc'],
    DEFAULTS: {
        downCpy: '25',
        interestCpy: '6.25',
        yearsCpy: '30',
        selectedCity: 'San Antonio',
        monthly_income: {
            laundryIncome: 0,
            storageIncome: 0,
            miscIncome: 0,
        },
        monthly_expense: {
            water: 0,
            Garbage: 0,
            Electric: 0,
            Gas: 0,
            HOAFees: 0,
            LawnSnow: 0,
            vacancy_percent: 5,
            units: 2,
            pricePerUnits: 50,
            capExPercent: 8,
            PropertyManageCostPercent: 10,
            Tax: 2,
            Insurance: 1.09,
            ClosingCost: 3000,
            RehabBudget: 5000,
            MiscOther: 0,
            RepairCostPercent: 1,
        },
    },
    CLIENT_SECRET: 'roi_signal_app_s3cr3t',
    CLIENT_ID: 'roi_signal_app',
};

export default CONST;
